### ISSUE TITLE
make error cpp starter 

### ISSUE THREAD

**Issue by ghost** [Bo-Yuan-Huang/cpp-project-template#4]
cloned the template and build the project using travis.yaml. I am getting following error

$ make
Scanning dependencies of target git_update
[  0%] Built target git_update
Scanning dependencies of target googletest
make[2]: *** No rule to make target `../external/googletest/googletest/src/gtest-all.cc', needed by `CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest-all.cc.o'.  Stop.
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
make: *** [all] Error 2
The command "make" exited with 2.

**Comment by ghost** [comment]
I think clone template does not clone the external directory that you have

**Comment by Bo-Yuan-Huang** [comment]
Did you do a submodule update?
